### ISSUE TITLE
License

### ISSUE THREAD

**Issue by asim** [wzhliang/xing#1]
If you lift code from somewhere like say for instance micro which is apache 2 licensed then you must show that. Please don't just steal code.

**Comment by wzhliang** [comment]
I'm fine with apache license but I am not aware of any stolen code. Please let me know where I did. Does importing count?

**Comment by asim** [comment]
You have a file named micro-types.go, the concepts are scarily similar to micro and you've also forked micro/protobuf and copied the implementation. It's one thing to be inspired by something, it's another to just pick things up, rip things out and build something without any credit to where you took it from.

**Comment by wzhliang** [comment]
I did fork micro/protobuf, but I did mention in REAME that where it originated. The `micor-type.go` file was only there to make things build and I didn't have a chance to clean it up. 

This is not at all meant to be competing/stealing from micro. As you might see, this is not as generic as go-micro - it's meant for a specific usage. If it appears it did, I'm sorry to hear it. I've added the same license file anyway. 

Please let me know if you'd like me to remove anything.

Best regards,

**Comment by wzhliang** [comment]
For the record, `micro-types.go` had `Option` and `CallOption`, both were empty in my code. `Option` was not used and is now removed. `CallOption` came from grpc.

**Comment by asim** [comment]
Please don't try defend your position. It's extremely apparent what you did. I'll leave you to it.

**Comment by wzhliang** [comment]
I'd really like to see if there is a lesson for me to learn here. Please email me if you like to discuss.
